// Serves a viewport-appropriate WebP where variants exist, falling back to the
// original file.
//
// Variants are generated by scripts/generate-images.mjs, which skips widths
// larger than the source rather than upscaling. The component therefore cannot
// assume every width exists - it consults the manifest the generator writes.
// Advertising a width that was never produced makes the browser request a file
// that is not there, and the SPA rewrite answers missing paths with index.html
// at HTTP 200, so the browser receives HTML where it expected an image and
// renders nothing.

import MANIFEST from '../data/image-manifest.json'

function srcSetFor(src) {
  const m = /^\/images\/([^/]+)\.(jpe?g|png)$/i.exec(src || '')
  if (!m) return null
  const widths = MANIFEST[m[1]]
  if (!widths?.length) return null
  return widths.map((w) => `/images/r/${m[1]}-${w}.webp ${w}w`).join(', ')
}

export default function Img({ src, alt, sizes = '100vw', className, ...rest }) {
  const srcSet = srcSetFor(src)
  if (!srcSet) return <img src={src} alt={alt} className={className} {...rest} />

  return (
    <picture>
      <source type="image/webp" srcSet={srcSet} sizes={sizes} />
      <img src={src} alt={alt} className={className} {...rest} />
    </picture>
  )
}
