// Serves a viewport-appropriate WebP where one exists, falling back to the
// original file. Variants are generated by scripts/generate-images.mjs into
// public/images/r/ at 640 and 1024 wide; anything larger keeps the original,
// which is smaller than a high-quality WebP at that size.

const VARIANT_WIDTHS = [640, 1024, 1440]

function variantsFor(src) {
  const m = /^\/images\/([^/]+)\.(jpe?g|png)$/i.exec(src || '')
  if (!m) return null
  const base = m[1]
  return VARIANT_WIDTHS.map((w) => `/images/r/${base}-${w}.webp ${w}w`).join(', ')
}

export default function Img({ src, alt, sizes = '100vw', className, ...rest }) {
  const srcSet = variantsFor(src)
  if (!srcSet) return <img src={src} alt={alt} className={className} {...rest} />

  return (
    <picture>
      <source type="image/webp" srcSet={srcSet} sizes={sizes} />
      <img src={src} alt={alt} className={className} {...rest} />
    </picture>
  )
}
